apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cgwi-php.fullname" . }}
  labels:
    {{- include "cgwi-php.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.app_config | nindent 2}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cgwi-php.fullname" . }}-fpm-upstream
  labels:
    {{- include "cgwi-php.labels" . | nindent 4 }}
data:
  _upstream-fpm.conf: |
    client_max_body_size 16M;
    upstream fpm {
        server localhost:9000;
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cgwi-php.fullname" . }}-caddy-config
  labels:
    {{- include "cgwi-php.labels" . | nindent 4 }}
data:
  Caddyfile: |
    http://:8000 {
    	request_body {
    		max_size {$CADDY_MAX_REQUEST_SIZE:16MB}
    	}
    	root * {$CADDY_PUBLIC_DIR:/srv/app/public}
    	encode
    	php_fastcgi {$CADDY_FPM:localhost:9000} {
    		read_timeout {$CADDY_READ_TIMEOUT:180s}
    	}
    	file_server
    }